language: node_js
node_js:
- 10
before_deploy:
- rm -rf dist
- babel src --out-dir dist
- npm version --no-git-tag-version --allow-same-version ${TRAVIS_TAG}
deploy:
  provider: npm
  email: sergio.perizote@gmail.com
  api_key:
    secure: nyZAT1p+35OWs+wPBFtxIU3EkAMFVYWY1XZC6wtbLJkGTGDxWQOp0k6iSdy9O9eOlzv5oYT0f4myqmhBGRILW3y5fahjojNUSQPrGESKqGyhOjVnG9Ty4mbsdMr0BCz/mRaiZroICQWTo8ATR/w0WIo8S9d37DolpAf2Ky0FqrkTkaWvgQFJA1Hf6L2ERLgQWtchnHeaGSM73NyCZjiRhOKzIDC2vc7VtzQkfik8L6GiPk6CJIN024CX/tGxOQqOKRcSfL9lw8U3Wa+drl2fFeDiza2ex55hwI6mDOY80am3HySqnpTK+T/4t0h4heeh/XlDCyr9mOm+tA+YwdiSu0Gd6xciEnsKyR0m2CZSJ9D7q7nDE4yvaV79X1uJpe0yeAySUtS9wKYRYOZtQBS+lt+pVwe4x5oQ4S7XAOA2pBiiVQJt56S7FrYaHjygD0TGQuwwC1blmcxCiGTO6jyCKNXh4MZHm82M/zjRNzFYRgPYWV369VFBEgI5XJxP2kwpLXysLxRez1IpkIeivZcTV2PkxJI1mLKwgYAs0vy2oeS8kT0IRNtAkopsM4j5LqD4DI1GlrwcP4pYXntiWeHrQefgomIsL2vRo4ubuTp7b37CE94ThGI4kKDmcom+Oae10RJcVWcIuAPWeN9y0REXelDiH+3O61UZHJmIxgFNjF0=
  on:
    tags: true
    repo: Perizote/network-barrier
  skip_cleanup: 'true'
