language: node_js
node_js:
- 10
before_deploy:
- rm -rf dist
- babel src --out-dir dist
- npm version --no-git-tag-version --allow-same-version ${TRAVIS_TAG}
deploy:
  provider: npm
  email: sergio.perizote@gmail.com
  api_key:
    secure: OECx9jCmt+G3S2FuiVHSH0aHxq8IYqzBJe0yytKzkHw5AuhVhfY6ua/LvApTHZ8HGjsktPm9cx845b4gR5mVPzDDyyPUv5lOvLm4ZgjMHHa+sD/n+c8lyGV11fncunzpigY8cYDjg5T/6kG4QEOGT92DG7nHJ5lpY64Vu3Tzeaxr3f0C4tKKyfnehyCIt0C0vSbMxu94+s6dlQu9uKnYmfNR+VdkdCwclkvXDmihprOH4bU+GWQq8x9fDuyNxnhvvntRU3M+tSHB9oUeVaNm4e8J5ZV60ZCPWgBlPNfwbN6yJ1SPZCA85Q8PZtTzdiOs30eqogzQoCLFRMfjDl4245OeSNiz5LV3RA4wWhv6emfedagIi2kf+gm2G5ZqjmmtKyn/215CDTPG6IeKoM+IKL/GfBUxsg3PGymFMFwSe39Pl37S9eiWvLqvXUZUs3cIF2246h1fBKdmSjd0mRKBpM/e8TwI9hc8eooPmGG1ViPp78TJOVq4JJmCJoSvkTQ15OuM6BEeyYK1JDW1+HxgUl9JaFvsbOfc0rG0zNOHixjimWem05eJZx+ysNRIQlyTQ9ezDD1CIW9wpuQTU2uzCBt3CHcKJkgoak20ozyyi9cygFH38b9IA2Z1sU9IFGVOHkLYyiwD3FQMFIDF9Vl3JDexCmO/Iqj+yRNAvuwsjEE=
  on:
    tags: true
    repo: Perizote/barrier
  skip_cleanup: 'true'
